# Generated by Django 4.2.20 on 2025-04-10 16:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default=datetime.datetime(2025, 4, 10, 16, 29, 5, 883623, tzinfo=datetime.timezone.utc), max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='dislike',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
